import 'package:Psynexa/models/chatbot/chatbot.dart';
import 'package:flutter/material.dart';
import 'package:Psynexa/assets.dart';
import 'package:Psynexa/constant/constant.dart';
import 'package:flutter_svg/svg.dart';
import 'package:grock/grock.dart';
import 'package:intl/intl.dart';
import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:Psynexa/riverpod/list_scaffold_riverpod.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

final ListRiverpod = ChangeNotifierProvider((ref) => listRiverpod());

class Autogenerated {
  String? nexa;

  Autogenerated({this.nexa});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    nexa = json['Nexa'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['Nexa'] = nexa;
    return data;
  }
}

class ChatBot extends ConsumerStatefulWidget {
  const ChatBot({super.key});

  @override
  ConsumerState<ChatBot> createState() => _ChatBotState();
}

class _ChatBotState extends ConsumerState<ChatBot> {
  TextEditingController text = TextEditingController();
  FocusNode _textFocusNode = FocusNode();

  @override
  Widget build(BuildContext context) {
    var watch = ref.watch(ListRiverpod);
    var read = ref.read(ListRiverpod);

    Future postMessage() async {
      final url = Uri.parse(
          '${Constant.domain}/ai/send_message_nexa'); // API'nin URL'sini buraya ekleyin

      final Map<String, String> headers = {
        'Content-Type': 'application/json',
      };

      final Map<String, String> body = {
        'message': text.text,
      };

      final String jsonBody = jsonEncode(body);
      text.clear();
      final response = await http.post(
        url,
        headers: headers,
        body: jsonBody,
      );

      if (response.statusCode == 200) {
        final data = json.decode(response.body);
        final resData = Autogenerated.fromJson(data);
        read.setChatList(chatModel(
            message: resData.nexa.toString(),
            time: DateTime.now(),
            role: 'bot'));
      }
    }

    return Scaffold(
      appBar: AppBar(
        toolbarHeight: 70,
        elevation: 0,
        centerTitle: true,
        title: Padding(
          padding: const EdgeInsets.only(top: 8.0),
          child: Hero(
            tag: 'chatgifhero',
            child: Container(
              width: 60,
              height: 60,
              decoration: BoxDecoration(
                image: DecorationImage(
                  image: AssetImage(Assets.images.nexaGIF),
                  fit: BoxFit.cover,
                ),
              ),
            ),
          ),
        ),
        leading: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 10.0),
          child: IconButton(
            padding: 19.allP,
            onPressed: () {
              Grock.back();
            },
            icon: const Icon(
              Icons.arrow_back_ios_rounded,
              size: 20,
            ),
            color: Constant.purple,
          ),
        ),
        backgroundColor: Constant.white,
      ),
      body: Padding(
        padding: const EdgeInsets.only(left: 10, right: 10, bottom: 25),
        child: Column(
          children: [
            Expanded(
                child: Column(
              children: [
                Expanded(
                  child: ListView.builder(
                    reverse: true,
                    physics: const BouncingScrollPhysics(),
                    padding: const EdgeInsets.only(bottom: 20),
                    itemCount: watch.chatlist.length,
                    itemBuilder: (BuildContext context, int index) {
                      return _messageWidget(
                        role: watch
                            .chatlist[watch.chatlist.length - index - 1].role,
                        date: DateFormat('HH:mm')
                            .format(watch
                                .chatlist[watch.chatlist.length - index - 1]
                                .time)
                            .toString(),
                        message: watch
                            .chatlist[watch.chatlist.length - index - 1]
                            .message,
                      );
                    },
                  ),
                ),
              ],
            )),
            Row(
              children: [
                Expanded(
                  child: Container(
                    padding:
                        const EdgeInsets.only(left: 19, right: 19, bottom: 15),
                    child: Row(
                      children: [
                        SizedBox(
                          height: 50,
                          width: MediaQuery.sizeOf(context).width - 123,
                          child: Padding(
                            padding: const EdgeInsets.symmetric(vertical: 3.0),
                            child: TextField(
                              textAlignVertical: TextAlignVertical.bottom,
                              controller: text,
                              focusNode: _textFocusNode,
                              onEditingComplete: null,
                              cursorColor: Constant.purple,
                              decoration: InputDecoration(
                                focusedBorder: OutlineInputBorder(
                                  borderSide: const BorderSide(
                                      color: Color(0xFFE8E6EA), width: 1),
                                  borderRadius: BorderRadius.circular(12),
                                ),
                                enabledBorder: OutlineInputBorder(
                                  borderSide: const BorderSide(
                                      color: Color(0xFFE8E6EA), width: 1),
                                  borderRadius: BorderRadius.circular(12),
                                ),
                                filled: true,
                                fillColor: Constant.white,
                                hintText: 'Mesajınız',
                                hintStyle: const TextStyle(
                                  fontSize: 14,
                                  fontWeight: FontWeight.w400,
                                  color: Color.fromARGB(175, 51, 51, 51),
                                  height: 1.4,
                                ),
                              ),
                            ),
                          ),
                        ),
                        const SizedBox(
                          width: 15,
                        ),
                        GrockContainer(
                          onTap: () {
                            read.setChatList(chatModel(
                                message: text.text,
                                time: DateTime.now(),
                                role: 'client'));

                            postMessage();
                          },
                          height: 44,
                          width: 44,
                          decoration: BoxDecoration(
                            color: Constant.white,
                            borderRadius: BorderRadius.circular(12),
                            border: Border.all(
                                color: const Color(0xFFE8E6EA), width: 1),
                          ),
                          child: Center(
                            child:
                                SvgPicture.asset(Assets.icons.icSendArrowSVG),
                          ),
                        ),
                      ],
                    ),
                  ),
                )
              ],
            )
          ],
        ),
      ),
    );
  }
}

class _messageWidget extends StatelessWidget {
  String role, message;
  String date;
  _messageWidget(
      {required this.role, required this.date, required this.message});

  @override
  Widget build(BuildContext context) {
    return ListTile(
      title: Align(
        alignment: role == 'bot' ? Alignment.centerLeft : Alignment.centerRight,
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment:
              role == 'bot' ? CrossAxisAlignment.start : CrossAxisAlignment.end,
          children: [
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 14),
              decoration: BoxDecoration(
                color: role == 'bot'
                    ? Constant.darkwhite
                    : const Color.fromARGB(73, 103, 71, 199),
                borderRadius: role == 'bot'
                    ? const BorderRadius.only(
                        bottomRight: Radius.circular(15),
                        topLeft: Radius.circular(15),
                        topRight: Radius.circular(15))
                    : const BorderRadius.only(
                        bottomLeft: Radius.circular(15),
                        topLeft: Radius.circular(15),
                        topRight: Radius.circular(15)),
              ),
              child: Text(
                message,
                style: const TextStyle(
                    color: Colors.black,
                    fontSize: 13.5,
                    fontWeight: FontWeight.w400,
                    fontFamily: 'Proxima Nova',
                    letterSpacing: -0.4),
              ),
            ),
            Padding(
              padding: const EdgeInsets.only(top: 6.0),
              child: Text(
                date,
                style: const TextStyle(
                    fontSize: 11,
                    fontWeight: FontWeight.w400,
                    color: Color.fromARGB(133, 51, 51, 51)),
              ),
            )
          ],
        ),
      ),
    );
  }
}
