import 'package:Psynexa/models/firebase_model.dart';
import 'package:Psynexa/services/firebase_service.dart';
import 'package:flutter/material.dart';
import 'package:Psynexa/assets.dart';
import 'package:Psynexa/constant/constant.dart';
import 'package:flutter_svg/svg.dart';
import 'package:grock/grock.dart';
import 'package:intl/intl.dart';
import 'dart:convert';
import 'package:http/http.dart' as http;

class Autogenerated {
  String? nexa;

  Autogenerated({this.nexa});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    nexa = json['Nexa'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['Nexa'] = this.nexa;
    return data;
  }
}

class ChatBot extends StatefulWidget {
  ChatBot({super.key});

  @override
  State<ChatBot> createState() => _ChatBotState();
}

class _ChatBotState extends State<ChatBot> {
  TextEditingController text = TextEditingController();
  FocusNode _textFocusNode = FocusNode();

  @override
  Widget build(BuildContext context) {
    @override
    void initState() {
      super.initState();
    }

    List<_chatModel> list = [
      _chatModel(message: 'sdadsds', time: DateTime.now(), role: 'bot'),
      _chatModel(message: 'sdadsds', time: DateTime.now(), role: 'bot'),
    ];
    Future postMessage() async {
      print(list.length);
      final url = Uri.parse(
          '${Constant.domain}/ai/send_message_nexa'); // API'nin URL'sini buraya ekleyin

      final Map<String, String> headers = {
        'Content-Type': 'application/json',
      };

      final Map<String, String> body = {
        'message': '${text.text}',
      };

      final String jsonBody = jsonEncode(body);

      final response = await http.post(
        url,
        headers: headers,
        body: jsonBody,
      );

      if (response.statusCode == 200) {
        final data = json.decode(response.body);
        final resData = Autogenerated.fromJson(data);
        list.add(_chatModel(
            message: resData.nexa.toString(),
            time: DateTime.now(),
            role: 'bot'));
        setState(() {
          list;
        });
        print('Başarıyla istek gönderildi. ${response.body}');
      } else {
        print('Hata: ${response.statusCode}');
      }
    }

    return Scaffold(
      appBar: AppBar(
        toolbarHeight: 70,
        elevation: 0,
        centerTitle: true,
        title: Padding(
          padding: const EdgeInsets.only(top: 8.0),
          child: Hero(
            tag: 'chatgifhero',
            child: Container(
              width: 60,
              height: 60,
              decoration: BoxDecoration(
                image: DecorationImage(
                  image: AssetImage(Assets.images.nexaGIF),
                  fit: BoxFit.cover,
                ),
              ),
            ),
          ),
        ),
        leading: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 10.0),
          child: IconButton(
            padding: 19.allP,
            onPressed: () {
              Grock.back();
            },
            icon: const Icon(
              Icons.arrow_back_ios_rounded,
              size: 20,
            ),
            color: Constant.purple,
          ),
        ),
        backgroundColor: Constant.white,
      ),
      body: Padding(
        padding: const EdgeInsets.only(left: 10, right: 10, bottom: 25),
        child: Column(
          children: [
            Expanded(
                child: Column(
              children: [
                Expanded(
                  child: ListView.builder(
                    reverse: true,
                    physics: BouncingScrollPhysics(),
                    padding: EdgeInsets.only(bottom: 20),
                    itemCount: list.length,
                    itemBuilder: (BuildContext context, int index) {
                      return _messageWidget(
                        role: list[index].role,
                        date: DateFormat('HH:mm')
                            .format(list[index].time)
                            .toString(),
                        message: list[index].message,
                      );
                    },
                  ),
                ),
              ],
            )),
            Row(
              children: [
                Expanded(
                  child: Container(
                    padding: EdgeInsets.only(left: 19, right: 19, bottom: 15),
                    child: Row(
                      children: [
                        SizedBox(
                          height: 50,
                          width: MediaQuery.sizeOf(context).width - 123,
                          child: Padding(
                            padding: const EdgeInsets.symmetric(vertical: 3.0),
                            child: TextField(
                              textAlignVertical: TextAlignVertical.bottom,
                              controller: text,
                              focusNode: _textFocusNode,
                              onEditingComplete: null,
                              cursorColor: Constant.purple,
                              decoration: InputDecoration(
                                focusedBorder: OutlineInputBorder(
                                  borderSide: const BorderSide(
                                      color: Color(0xFFE8E6EA), width: 1),
                                  borderRadius: BorderRadius.circular(12),
                                ),
                                enabledBorder: OutlineInputBorder(
                                  borderSide: const BorderSide(
                                      color: Color(0xFFE8E6EA), width: 1),
                                  borderRadius: BorderRadius.circular(12),
                                ),
                                filled: true,
                                fillColor: Constant.white,
                                hintText: 'Mesajınız',
                                hintStyle: TextStyle(
                                  fontSize: 14,
                                  fontWeight: FontWeight.w400,
                                  color: Color.fromARGB(175, 51, 51, 51),
                                  height: 1.4,
                                ),
                              ),
                            ),
                          ),
                        ),
                        SizedBox(
                          width: 15,
                        ),
                        GrockContainer(
                          onTap: () async {
                            list.add(_chatModel(
                                message: text.text,
                                time: DateTime.now(),
                                role: 'client'));
                            await postMessage();
                            setState(() {
                              /*DateTime now = DateTime.now();
                              _chatModel.insert(
                                0,
                                _chatBotModel(
                                    message: text.text,
                                    hour: '${now.hour}:${now.minute}',
                                    rol: 'user'),
                              );
                              text.text = '';
                              FocusScope.of(context)
                                  .requestFocus(_textFocusNode);*/
                            });
                          },
                          height: 44,
                          width: 44,
                          decoration: BoxDecoration(
                            color: Constant.white,
                            borderRadius: BorderRadius.circular(12),
                            border:
                                Border.all(color: Color(0xFFE8E6EA), width: 1),
                          ),
                          child: Center(
                            child:
                                SvgPicture.asset(Assets.icons.icSendArrowSVG),
                          ),
                        ),
                      ],
                    ),
                  ),
                )
              ],
            )
          ],
        ),
      ),
    );
  }
}

class _messageWidget extends StatelessWidget {
  String role, message;
  String date;
  _messageWidget(
      {required this.role, required this.date, required this.message});

  @override
  Widget build(BuildContext context) {
    return ListTile(
      title: Align(
        alignment: role == 'bot' ? Alignment.centerLeft : Alignment.centerRight,
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment:
              role == 'bot' ? CrossAxisAlignment.start : CrossAxisAlignment.end,
          children: [
            Container(
              padding: EdgeInsets.symmetric(horizontal: 20, vertical: 14),
              decoration: BoxDecoration(
                color: role == 'bot'
                    ? Constant.darkwhite
                    : Color.fromARGB(73, 103, 71, 199),
                borderRadius: role == 'bot'
                    ? BorderRadius.only(
                        bottomRight: Radius.circular(15),
                        topLeft: Radius.circular(15),
                        topRight: Radius.circular(15))
                    : BorderRadius.only(
                        bottomLeft: Radius.circular(15),
                        topLeft: Radius.circular(15),
                        topRight: Radius.circular(15)),
              ),
              child: Text(
                message,
                style: TextStyle(
                    color: Colors.black,
                    fontSize: 13.5,
                    fontWeight: FontWeight.w400,
                    fontFamily: 'Proxima Nova',
                    letterSpacing: -0.4),
              ),
            ),
            Padding(
              padding: const EdgeInsets.only(top: 6.0),
              child: Text(
                date,
                style: TextStyle(
                    fontSize: 11,
                    fontWeight: FontWeight.w400,
                    color: Color.fromARGB(133, 51, 51, 51)),
              ),
            )
          ],
        ),
      ),
    );
  }
}

class _chatModel {
  String message;
  DateTime time;
  String role;

  _chatModel({required this.message, required this.time, required this.role});
}

/**/